"""
Django settings for Sakarela_DJANGO project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import datetime
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='',
    cast=lambda v: [h.strip() for h in v.split(',') if h.strip()]
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sakarela',
    'store'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Sakarela_DJANGO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_items_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'Sakarela_DJANGO.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)  # ensure it exists at startup

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "econt_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "econt.log"),
            "maxBytes": 2_000_000,
            "backupCount": 5,
            "formatter": "simple",
        },
        "payments_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "payments.log"),
            "maxBytes": 2_000_000,
            "backupCount": 5,
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"}
    },
    "loggers": {
        "econt": {"handlers": ["econt_file", "console"], "level": "INFO"},
        "payments": {"handlers": ["payments_file", "console"], "level": "INFO"},
    },
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_VERSION = datetime.now().strftime("%Y%m%d%H%M%S")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MYPOS_CLIENT_NUMBER = config('MYPOS_CLIENT_NUMBER')
MYPOS_TERMINAL_ID = config('MYPOS_TERMINAL_ID')
MYPOS_PRIVATE_KEY_PATH = config('MYPOS_PRIVATE_KEY_PATH')

# -----------------------------------------------------------------------------
# myPOS PSD2 sandbox (global TPP) settings
# -----------------------------------------------------------------------------

# "API Key" / clientNumber
MYPOS_SANDBOX_CLIENT_NUMBER = config('MYPOS_SANDBOX_CLIENT_NUMBER')
MYPOS_SANDBOX_CLIENT_SECRET = config('MYPOS_SANDBOX_CLIENT_SECRET')
MYPOS_SANDBOX_OAUTH_TOKEN_URL = config('MYPOS_SANDBOX_OAUTH_TOKEN_URL')
MYPOS_SANDBOX_API_BASE_URL = config('MYPOS_SANDBOX_API_BASE_URL')

MYPOS_SID = config('MYPOS_SID')
MYPOS_WALLET = config('MYPOS_WALLET')
MYPOS_KEYINDEX = config('MYPOS_KEYINDEX')
MYPOS_METHOD = config('MYPOS_METHOD')
MYPOS_VERSION = config('MYPOS_VERSION')
# change these to your actual domain or localhost in dev:
MYPOS_RESPONSE_URL = config('MYPOS_RESPONSE_URL')
MYPOS_CALLBACK_URL = config('MYPOS_CALLBACK_URL')
MYPOS_BASE_URL = config('MYPOS_BASE_URL')

# Econt (from .env)
ECONT_USER = os.getenv("ECONT_USER")
ECONT_PASS = os.getenv("ECONT_PASS")

# Prefer the explicit JSON endpoint; fall back to demo if missing
ECONT_CREATE_LABEL_URL = os.getenv(
    "ECONT_CREATE_LABEL_URL",
    "https://ee.econt.com/services/Shipments/LabelService.createLabel.json",
)

# Optional sender defaults used by build_econt_label_payload()
ECONT_SENDER_NAME = os.getenv("ECONT_SENDER_NAME", "Сакарела")
ECONT_SENDER_PHONE = os.getenv("ECONT_SENDER_PHONE", "+359878630943")
ECONT_SENDER_CITY = os.getenv("ECONT_SENDER_CITY", "Бургас")
ECONT_SENDER_POSTCODE = os.getenv("ECONT_SENDER_POSTCODE", "8000")

# --- Backward-compat aliases (safe no-ops if you referenced old names) ---
ECONT_USERNAME = os.getenv("ECONT_USERNAME", ECONT_USER or "")
ECONT_PASSWORD = os.getenv("ECONT_PASSWORD", ECONT_PASS or "")
ECONT_LABEL_URL = os.getenv("ECONT_LABEL_URL", "https://demo.econt.com/ee/services")

# Google Maps API settings
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='YOUR_API_KEY')

# TRUSTED ORIGINS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    "https://www.mypos.com/vmp/checkout",
    "https://dev.sakarela.com",
]
CSRF_COOKIE_SECURE = True  # if your site is HTTPS-only
SESSION_COOKIE_SECURE = True
