# Generated by Django 5.2.1 on 2025-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='store/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(blank=True)),
                ('storage', models.CharField(blank=True, max_length=255)),
                ('nutritional_value', models.TextField(blank=True, verbose_name='Nutritional Value (Table HTML)')),
            ],
        ),
    ]
