# Generated by Django 5.2.1 on 2025-06-10 06:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Computed sum of all order items.', max_digits=12),
        ),
    ]
