# Generated by Django 5.2.1 on 2025-06-13 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_delivery_status_order_delivery_tracking_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(help_text='грамове')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='оставете празно, ако няма промо', max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_options', to='store.product')),
            ],
            options={
                'ordering': ('weight',),
                'unique_together': {('product', 'weight')},
            },
        ),
    ]
