# Generated by Django 5.2.1 on 2025-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_packagingoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingoption',
            name='weight',
            field=models.FloatField(help_text='грамове'),
        ),
    ]
