# Generated by Django 5.2.1 on 2025-06-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_packagingoption_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='econt_shipment_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='label_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
