# Generated by Django 5.1.1 on 2025-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_econt_shipment_num_order_label_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingoption',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Отбележете, за да активирате sale_price като текуща цена'),
        ),
    ]
