# Generated by Django 5.1.1 on 2025-08-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_packagingoption_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text="Label/Badge for the product (e.g., 'ОВЧЕ МЛЯКО', 'БДС', 'КОЗЕ МЛЯКО', 'КРАВЕ МЛЯКО', 'С ПОДПРАВКИ')", max_length=100, null=True),
        ),
    ]
