# Generated by Django 5.1.1 on 2025-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('map_x_pct', models.DecimalField(decimal_places=2, default=50, help_text='Left offset in %', max_digits=5)),
                ('map_y_pct', models.DecimalField(decimal_places=2, default=50, help_text='Top offset in %', max_digits=5)),
                ('show_on_map', models.BooleanField(default=True)),
            ],
        ),
    ]
