# Generated by Django 5.1.1 on 2025-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
