# Generated by Django 5.1.1 on 2025-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_store_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='map_url',
            field=models.URLField(blank=True, verbose_name='Линк към карта'),
        ),
    ]
