# Generated by Django 5.1.1 on 2025-10-17 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_store_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон за контакт (пример: +359888123456 или 0888123456).', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Въведете валиден телефон (+359XXXXXXXXX или 0XXXXXXXXX).', regex='^(?:\\+359\\d{9}|0\\d{9})$')]),
        ),
    ]
