# Generated by Django 5.1.1 on 2025-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес за фактуриране'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_bulstat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='БУЛСТАТ / ЕИК'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_mol',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='МОЛ'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фирма'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_company',
            field=models.BooleanField(default=False, help_text='Отбележете, ако желаете фактура към фирма.', verbose_name='Фактура към фирма?'),
        ),
    ]
