# Generated by Django 5.1.1 on 2025-11-13 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_company_address_order_company_bulstat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Общо тегло на поръчката в килограми.', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_weight_g',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Тегло на единица (грамове) за този артикул в поръчката.', max_digits=8),
        ),
    ]
