import os
import sys
from pathlib import Path

def setup_environment():
    """Set up the development environment"""
    print("Setting up development environment...")
    
    # Get the current directory
    base_dir = Path(__file__).resolve().parent
    
    # Create mypos directory if it doesn't exist
    mypos_dir = base_dir / 'mypos'
    mypos_dir.mkdir(exist_ok=True)
    
    # Check if private key exists
    key_path = mypos_dir / 'private_key.pem'
    if not key_path.exists():
        print("Private key not found, will be generated by generate_key.py")
    
    print("Environment setup complete!")
    return 0

if __name__ == '__main__':
    sys.exit(setup_environment()) 