# Generated by Django 5.2.1 on 2025-06-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0002_product_ingredients_product_nutrition_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
