# Generated by Django 5.2.1 on 2025-06-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0003_alter_product_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
