# Generated by Django 5.2.1 on 2025-06-06 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nutrition',
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.CharField(help_text='Example: 352kcal / 1462kJ', max_length=50)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('saturated_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('salt', models.DecimalField(decimal_places=1, max_digits=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='sakarela.product')),
            ],
        ),
    ]
