# Generated by Django 5.2.1 on 2025-06-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0005_remove_product_nutrition_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('ingredients', models.TextField(help_text='List of ingredients, one per line')),
                ('cook_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('steps', models.TextField(help_text='Step-by-step instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
