# Generated by Django 5.2.1 on 2025-06-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0006_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(default=1, help_text='The product this recipe is for', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='sakarela.product'),
        ),
    ]
