# Generated by Django 5.1.1 on 2025-07-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0007_recipe_product'),
        ('store', '0011_order_econt_shipment_num_order_label_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_product',
            field=models.OneToOneField(blank=True, help_text='If set, shows a ‘Buy online’ button', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_product', to='store.product'),
        ),
    ]
