# Generated by Django 5.1.1 on 2025-08-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0008_product_store_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='steps',
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text='Example: Step 1, Step 2, etc.', max_length=100)),
                ('step_content', models.TextField(help_text='The content/instructions for this step')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the step (1, 2, 3, etc.)')),
                ('recipe', models.ForeignKey(help_text='The recipe this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_steps', to='sakarela.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
