# Generated by Django 5.1.1 on 2025-08-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0009_remove_recipe_steps_recipestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(help_text='Name of the ingredient/product', max_length=200)),
                ('amount', models.CharField(help_text='Amount/quantity of the ingredient', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the ingredient (1, 2, 3, etc.)')),
                ('recipe', models.ForeignKey(help_text='The recipe this ingredient belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='sakarela.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
