# Generated by Django 5.1.1 on 2025-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0010_remove_recipe_ingredients_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='appliance',
            field=models.CharField(default=0, help_text='Cooking equipment/appliances needed', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, help_text='Number of servings'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.TextField(default='blank', help_text='Brief description of the recipe', max_length=300),
            preserve_default=False,
        ),
    ]
