# Generated by Django 5.1.1 on 2025-08-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakarela', '0011_recipe_appliance_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kashkaval', 'Кашкавал'), ('sirene', 'Сирене'), ('yogurt', 'Йогурт'), ('milk', 'Мляко'), ('other', 'Други')], default='other', help_text='Тип на продукта', max_length=20),
        ),
    ]
